// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt9Jfre5lJNbShLNe6AjrOKDpHbjN-Hv4',
    appId: '1:971157123069:web:6346e73a15514a7e32f394',
    messagingSenderId: '971157123069',
    projectId: 'classroom-instagram-app',
    authDomain: 'classroom-instagram-app.firebaseapp.com',
    storageBucket: 'classroom-instagram-app.firebasestorage.app',
    measurementId: 'G-PG68BQ04Y1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQU9zrwVaCeM8jclEgIGf6OY9YDsw4BwI',
    appId: '1:971157123069:android:295734acb66ad5d232f394',
    messagingSenderId: '971157123069',
    projectId: 'classroom-instagram-app',
    storageBucket: 'classroom-instagram-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz_xwW62K6t-iGQbJ1B0jKxtLvbNLIbT8',
    appId: '1:971157123069:ios:c19781cabd2792fc32f394',
    messagingSenderId: '971157123069',
    projectId: 'classroom-instagram-app',
    storageBucket: 'classroom-instagram-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
